source "https://rubygems.org"

gem 'cocoapods', '1.16.2'
gem "fastlane"
gem "dotenv"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile('fastlane/Pluginfile') if File.exist?(plugins_path)
