# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

TEMP_KEYCHAIN_USER = 'temp_keychain'
TEMP_KEYCHAIN_PASSWORD = 'temp_keychain_password'

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do

  desc "Build and upload iOS app to TestFlight"
  lane :beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    setup_ci if ENV["CI"]
    ensure_temp_keychain(keychain_name, keychain_password)

    app_store_connect_api_key(
        key_id: ENV["APPSTORE_KEY_ID"],
        issuer_id: ENV["APPSTORE_KEY_ISSUER_ID"],
        key_content: ENV["APPSTORE_P8_KEY_CONTENT"],
        duration: 200,
        is_key_content_base64: true
    )

    remove_provisioning_profile(app_identifier: ENV["APP_IDENTIFIER"], type: "appstore")
    raise "BUILD_NUMBER is not set" unless ENV["BUILD_NUMBER"]

    match(
        type: "appstore",
        readonly: false,
        app_identifier: ENV["APP_IDENTIFIER"]
    )

    update_code_signing_settings(
        use_automatic_signing: false,
        path: "Runner.xcodeproj",
        team_id: ENV["TEAM_ID"],
        bundle_identifier: ENV["APP_IDENTIFIER"],
        profile_name: ENV["sigh_#{ENV["APP_IDENTIFIER"]}_appstore_profile-name"]
    )

    sh("flutter pub get")
    flutter_versioner(
        pubspec_file_path: "../pubspec.yaml",
        value: ENV["BUILD_NUMBER"],
        version_component: "version_code"
    )
    cocoapods

    build_app(
        workspace: "Runner.xcworkspace",
        scheme: "Runner",
        xcargs: "DEVELOPMENT_TEAM=#{ENV['TEAM_ID']}"
        export_method: "app-store"
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)
    delete_temp_keychain(keychain_name)
    puts "iOS build #{lane_context[SharedValues::BUILD_NUMBER]} was uploaded to Test Flight"
  end

end
